### PR TITLE
Update SecuredEventInterceptor.cfc

### PR DESCRIPTION
**Pull request by gpickin**
Fixing for ColdBox 5 changes - including Virtual Inheritance Bug

### CODE REVIEW

**Comment by bdw429s** [comment]
@gpickin It would appear this isn't compat with ColdBox 4.  All the unit tests are failing and they run on ColdBox 4.

**Comment by elpete** [comment]
Yikes...do we need to start running tests against ColdBox 4 _and_ ColdBox 5?!? That puts us up to 10–12 matrixes.

**Comment by bdw429s** [comment]
Minimally, we need to update all our tests to Coldbox 5.  I think pretty much all of them are on ColdBox 4 still.  But as long as we're supporting ColdBox 4 I'd say we have to options:
1) run all builds on Coldbox 4 and make sure we keep it all compat
2) Do a major version bump and simply advertise that if you want to use ColdBox 4 you need to stay back on the previous major version.  (would also require all Coldbox 5 users to manually upgrade past that bump too)

**Comment by gpickin** [comment]
So, whats the most efficient way to make this backwards compat?
Should we check to see if the method exists with a structKeyExists, to determine the version?

```
if( structKeyExists( handlerService, "getRegisteredHandler" ) ){
    var handlerBean = handlerService.getRegisteredHandler( event.getCurrentEvent() );
} else {
    var handlerBean = handlerService.getHandlerBean( event.getCurrentEvent() );
}
var handler = handlerService.getHandler(
    handlerBean,
    event
);
```

**Comment by elpete** [comment]
You could inject the ColdBox version through the settings injection?

**Comment by gpickin** [comment]
In ColdBox 5 @lmajano said we can do this

beanHandler.getActionMetadata( "cacheTimeout", "" );
beanHandler.getHandlerMetadata( "cacheTimeout", "" );

But its still a lot of processing to get here, but we don't need to do the getMetaData( beanHandler ) call

**Comment by gpickin** [comment]
Also, preProcess ignores the runEvent stuff.
Eric, do we want this to handle runEvent as well? 
Its not very preformant so Luis advised against it for now.

He is asking if you want to meet to discuss, and update this module, make the most of the ColdBox 5 updates?

**Comment by gpickin** [comment]
I can get the version with coldbox:fwSetting:version
Updated for that, just checking for the major version.
Better @elpete

**Comment by elpete** [comment]
Is this where we want it, @gpickin?

**Pull request merged**
